gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/box2d.c -fno-common -DPIC -o .libs/lwgeom/box2d.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/g_box.c -fno-common -DPIC -o .libs/lwgeom/g_box.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/g_serialized.c -fno-common -DPIC -o .libs/lwgeom/g_serialized.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/g_util.c -fno-common -DPIC -o .libs/lwgeom/g_util.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/libtgeom.c -fno-common -DPIC -o .libs/lwgeom/libtgeom.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwalgorithm.c -fno-common -DPIC -o .libs/lwgeom/lwalgorithm.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwcircstring.c -fno-common -DPIC -o .libs/lwgeom/lwcircstring.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwcollection.c -fno-common -DPIC -o .libs/lwgeom/lwcollection.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwcompound.c -fno-common -DPIC -o .libs/lwgeom/lwcompound.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwcurvepoly.c -fno-common -DPIC -o .libs/lwgeom/lwcurvepoly.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwgeodetic.c -fno-common -DPIC -o .libs/lwgeom/lwgeodetic.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwgeom.c -fno-common -DPIC -o .libs/lwgeom/lwgeom.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwgeom_api.c -fno-common -DPIC -o .libs/lwgeom/lwgeom_api.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwgeom_debug.c -fno-common -DPIC -o .libs/lwgeom/lwgeom_debug.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwgeom_geos.c -fno-common -DPIC -o .libs/lwgeom/lwgeom_geos.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwgeom_geos_clean.c -fno-common -DPIC -o .libs/lwgeom/lwgeom_geos_clean.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwgeom_geos_node.c -fno-common -DPIC -o .libs/lwgeom/lwgeom_geos_node.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwgeom_geos_split.c -fno-common -DPIC -o .libs/lwgeom/lwgeom_geos_split.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwgeom_transform.c -fno-common -DPIC -o .libs/lwgeom/lwgeom_transform.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwhomogenize.c -fno-common -DPIC -o .libs/lwgeom/lwhomogenize.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwin_wkb.c -fno-common -DPIC -o .libs/lwgeom/lwin_wkb.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwin_wkt.c -fno-common -DPIC -o .libs/lwgeom/lwin_wkt.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwin_wkt_lex.c -fno-common -DPIC -o .libs/lwgeom/lwin_wkt_lex.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwin_wkt_parse.c -fno-common -DPIC -o .libs/lwgeom/lwin_wkt_parse.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwline.c -fno-common -DPIC -o .libs/lwgeom/lwline.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwlinearreferencing.c -fno-common -DPIC -o .libs/lwgeom/lwlinearreferencing.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwmcurve.c -fno-common -DPIC -o .libs/lwgeom/lwmcurve.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwmline.c -fno-common -DPIC -o .libs/lwgeom/lwmline.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwmpoint.c -fno-common -DPIC -o .libs/lwgeom/lwmpoint.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwmpoly.c -fno-common -DPIC -o .libs/lwgeom/lwmpoly.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwmsurface.c -fno-common -DPIC -o .libs/lwgeom/lwmsurface.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwout_geojson.c -fno-common -DPIC -o .libs/lwgeom/lwout_geojson.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwout_gml.c -fno-common -DPIC -o .libs/lwgeom/lwout_gml.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwout_kml.c -fno-common -DPIC -o .libs/lwgeom/lwout_kml.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwout_svg.c -fno-common -DPIC -o .libs/lwgeom/lwout_svg.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwout_wkb.c -fno-common -DPIC -o .libs/lwgeom/lwout_wkb.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwout_wkt.c -fno-common -DPIC -o .libs/lwgeom/lwout_wkt.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwout_x3d.c -fno-common -DPIC -o .libs/lwgeom/lwout_x3d.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwpoint.c -fno-common -DPIC -o .libs/lwgeom/lwpoint.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwpoly.c -fno-common -DPIC -o .libs/lwgeom/lwpoly.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwprint.c -fno-common -DPIC -o .libs/lwgeom/lwprint.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwpsurface.c -fno-common -DPIC -o .libs/lwgeom/lwpsurface.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwsegmentize.c -fno-common -DPIC -o .libs/lwgeom/lwsegmentize.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwspheroid.c -fno-common -DPIC -o .libs/lwgeom/lwspheroid.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwtin.c -fno-common -DPIC -o .libs/lwgeom/lwtin.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwtree.c -fno-common -DPIC -o .libs/lwgeom/lwtree.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwtriangle.c -fno-common -DPIC -o .libs/lwgeom/lwtriangle.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/lwutil.c -fno-common -DPIC -o .libs/lwgeom/lwutil.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/measures.c -fno-common -DPIC -o .libs/lwgeom/measures.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/measures3d.c -fno-common -DPIC -o .libs/lwgeom/measures3d.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/ptarray.c -fno-common -DPIC -o .libs/lwgeom/ptarray.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/snprintf.c -fno-common -DPIC -o .libs/lwgeom/snprintf.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/stringbuffer.c -fno-common -DPIC -o .libs/lwgeom/stringbuffer.o
gcc -g -O2 -fno-common -DPIC -Wall -Wmissing-prototypes -I..\geos\geos\include -c lwgeom/vsprintf.c -fno-common -DPIC -o .libs/lwgeom/vsprintf.o
